In [1]:
import torch
import torch.nn as nn

pred_y1 = torch.tensor([1.], requires_grad=True)
y1 = torch.tensor([5.], requires_grad=True)
pred_y2 = torch.tensor([2.], requires_grad=True)
y2 = torch.tensor([4.], requires_grad=True)


loss_1 = y1**2 - pred_y1**2
loss_2 = y2**3 - pred_y2**3

print(loss_1)
#tensor([24.], grad_fn=<SubBackward0>)
print(loss_2)
#tensor([56.], grad_fn=<SubBackward0>)

# loss_1에 대해서 backward을 했을 때,
loss_1.backward()

# 다음과 같이, backward를 실시한다면, 각 tensor안에 grad attribute안에
# loss_1에서 y1, pred_y1에 대한 편미분 값을 저장하게 된다.

print(pred_y1.grad)
#tensor([-2.])
print(y1.grad)
#tensor([10.])

loss_2.backward()

# loss_2에 대해 backward
print(pred_y2.grad)
#tensor([-12.])
print(y2.grad)
#tensor([48.])

# 각각 backward를 진행했을 때, 각 텐서의 grad 안에 미분 값을 저장하게 됩니다.

tensor([24.], grad_fn=<SubBackward0>)
tensor([56.], grad_fn=<SubBackward0>)
tensor([-2.])
tensor([10.])
tensor([-12.])
tensor([48.])


In [2]:
import torch
import torch.nn as nn

pred_y1 = torch.tensor([1.], requires_grad=True)
y1 = torch.tensor([5.], requires_grad=True)
pred_y2 = torch.tensor([2.], requires_grad=True)
y2 = torch.tensor([4.], requires_grad=True)


loss_1 = y1**2 - pred_y1**2
loss_2 = y2**3 - pred_y2**3

print(loss_1)
#tensor([24.], grad_fn=<SubBackward0>)
print(loss_2)
#tensor([56.], grad_fn=<SubBackward0>)
loss = loss_1 + loss_2
print(loss)
# tensor([80.], grad_fn=<AddBackward0>)

# loss = loss_1 + loss_2에 대해서 backward()를 했을 때,
loss.backward()

# 각 loss에서 진행했던 backward() 값과 동일하게 나옵니다.
print(pred_y1.grad)
#tensor([-2.])
print(y1.grad)
#tensor([10.])
print(pred_y2.grad)
#tensor([-12.])
print(y2.grad)
#tensor([48.])

# 즉, loss를 합해도 동일한 gradient를 가지게 됩니다.

tensor([24.], grad_fn=<SubBackward0>)
tensor([56.], grad_fn=<SubBackward0>)
tensor([80.], grad_fn=<AddBackward0>)
tensor([-2.])
tensor([10.])
tensor([-12.])
tensor([48.])


In [3]:
import torch
import torch.nn as nn

pred_y1 = torch.tensor([1., 2., 3.], requires_grad=True)
y1 = torch.tensor([5., 6., 7.], requires_grad=True)

loss_1 = y1**2 - pred_y1**2

print(loss_1)
#tensor([24., 32., 40.], grad_fn=<SubBackward0>)

loss_1.backward()
# RuntimeError: grad can be implicitly created only for scalar outputs

tensor([24., 32., 40.], grad_fn=<SubBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

In [4]:
loss_1 = (y1**2 - pred_y1**2).sum()
loss_1.backward()

print(pred_y1.grad)
#tensor([-2., -4., -6.])
print(y1.grad)
#tensor([10., 12., 14.])

tensor([-2., -4., -6.])
tensor([10., 12., 14.])
